import type { TikzTemplate } from '../index'

// === Math templates (29) ===
import { TEN_FRAMES_TEMPLATE } from './ten-frames'
import { NUMBER_BONDS_TEMPLATE } from './number-bonds'
import { NUMBER_LINES_TEMPLATE } from './number-lines'
import { BAR_MODELS_TEMPLATE } from './bar-models'
import { FRACTION_CIRCLES_TEMPLATE } from './fraction-circles'
import { FRACTION_BARS_TEMPLATE } from './fraction-bars'
import { AREA_MODELS_TEMPLATE } from './area-models'
import { ARRAYS_GRIDS_TEMPLATE } from './arrays-grids'
import { PLACE_VALUE_TEMPLATE } from './place-value'
import { SHAPES_BASIC_TEMPLATE } from './shapes-basic'
import { SHAPES_CLASSIFIED_TEMPLATE } from './shapes-classified'
import { ANGLES_LINES_TEMPLATE } from './angles-lines'
import { BAR_GRAPHS_TEMPLATE } from './bar-graphs'
import { LINE_PLOTS_TEMPLATE } from './line-plots'
import { COORDINATE_PLANE_TEMPLATE } from './coordinate-plane'
import { FACTOR_TREES_TEMPLATE } from './factor-trees'
import { LONG_DIVISION_TEMPLATE } from './long-division'
import { VOLUME_NETS_TEMPLATE } from './volume-nets'
import { TAPE_DIAGRAMS_TEMPLATE } from './tape-diagrams'
import { DOUBLE_NUMBER_LINES_TEMPLATE } from './double-number-lines'
import { PERCENTAGE_GRIDS_TEMPLATE } from './percentage-grids'
import { BOX_PLOTS_TEMPLATE } from './box-plots'
import { DOT_PLOTS_HISTOGRAMS_TEMPLATE } from './dot-plots-histograms'
import { SYMMETRY_TEMPLATE } from './symmetry'
import { TALLY_MARKS_TEMPLATE } from './tally-marks'
import { CLOCK_FACES_TEMPLATE } from './clock-faces'
import { COIN_MONEY_TEMPLATE } from './coin-money'
import { EQUATION_BALANCE_TEMPLATE } from './equation-balance'
import { MEASUREMENT_RULER_TEMPLATE } from './measurement-ruler'
import { SKIP_COUNTING_TEMPLATE } from './skip-counting'
import { THREE_D_SHAPES_TEMPLATE } from './3d-shapes'
import { PERIMETER_AREA_ELEMENTARY_TEMPLATE } from './perimeter-area-elementary'
import { EVEN_ODD_NUMBERS_TEMPLATE } from './even-odd-numbers'
import { MULTIPLICATION_TABLE_TEMPLATE } from './multiplication-table'
import { EXPANDED_FORM_TEMPLATE } from './expanded-form'
import { ELAPSED_TIME_TEMPLATE } from './elapsed-time'
import { PROBABILITY_ELEMENTARY_TEMPLATE } from './probability-elementary'
import { PATTERN_SEQUENCES_ELEMENTARY_TEMPLATE } from './pattern-sequences-elementary'
import { MEASUREMENT_CONVERSION_TEMPLATE } from './measurement-conversion'
import { INPUT_OUTPUT_TABLE_TEMPLATE } from './input-output-table'
import { ROUNDING_NUMBER_LINE_TEMPLATE } from './rounding-number-line'
import { COMPARING_ORDERING_NUMBERS_TEMPLATE } from './comparing-ordering-numbers'

// === Life Science templates (10) ===
import { LIFE_CYCLES_TEMPLATE } from './life-cycles'
import { FOOD_CHAINS_WEBS_TEMPLATE } from './food-chains-webs'
import { PLANT_ANATOMY_TEMPLATE } from './plant-anatomy'
import { ANIMAL_CLASSIFICATION_TEMPLATE } from './animal-classification'
import { HUMAN_BODY_SYSTEMS_TEMPLATE } from './human-body-systems'
import { BASIC_CELLS_TEMPLATE } from './basic-cells'
import { HABITATS_ECOSYSTEMS_TEMPLATE } from './habitats-ecosystems'
import { ANIMAL_ADAPTATIONS_TEMPLATE } from './animal-adaptations'
import { HIBERNATION_MIGRATION_TEMPLATE } from './hibernation-migration'
import { POLLINATION_PHOTOSYNTHESIS_TEMPLATE } from './pollination-photosynthesis'
import { INHERITED_LEARNED_TRAITS_TEMPLATE } from './inherited-learned-traits'

// === Earth & Space Science templates (13) ===
import { WATER_CYCLE_TEMPLATE } from './water-cycle'
import { ROCK_CYCLE_TEMPLATE } from './rock-cycle'
import { WEATHER_CLOUDS_TEMPLATE } from './weather-clouds'
import { SOLAR_SYSTEM_TEMPLATE } from './solar-system'
import { MOON_PHASES_TEMPLATE } from './moon-phases'
import { EARTH_LAYERS_TEMPLATE } from './earth-layers'
import { SEASONS_EARTH_TILT_TEMPLATE } from './seasons-earth-tilt'
import { LANDFORMS_TEMPLATE } from './landforms'
import { EROSION_WEATHERING_TEMPLATE } from './erosion-weathering'
import { SOIL_LAYERS_TEMPLATE } from './soil-layers'
import { FOSSIL_FORMATION_TEMPLATE } from './fossil-formation'
import { RENEWABLE_NONRENEWABLE_TEMPLATE } from './renewable-nonrenewable'
import { RECYCLING_CONSERVATION_TEMPLATE } from './recycling-conservation'

// === Physical Science templates (9) ===
import { FIVE_SENSES_TEMPLATE } from './five-senses'
import { STATES_OF_MATTER_TEMPLATE } from './states-of-matter'
import { SIMPLE_MACHINES_TEMPLATE } from './simple-machines'
import { MAGNETS_TEMPLATE } from './magnets'
import { LIGHT_OPTICS_TEMPLATE } from './light-optics'
import { SOUND_WAVES_TEMPLATE } from './sound-waves'
import { ENERGY_TYPES_TEMPLATE } from './energy-types'
import { FORCES_MOTION_ELEMENTARY_TEMPLATE } from './forces-motion-elementary'
import { SIMPLE_CIRCUITS_TEMPLATE } from './simple-circuits'

// === Social Studies templates (10) ===
import { TIMELINES_TEMPLATE } from './timelines'
import { MAP_ELEMENTS_TEMPLATE } from './map-elements'
import { GOVERNMENT_STRUCTURE_TEMPLATE } from './government-structure'
import { COMMUNITY_MAP_TEMPLATE } from './community-map'
import { FAMILY_TREE_TEMPLATE } from './family-tree'
import { WORLD_CONTINENTS_TEMPLATE } from './world-continents'
import { ECONOMICS_ELEMENTARY_TEMPLATE } from './economics-elementary'
import { MAP_GRID_COORDINATES_TEMPLATE } from './map-grid-coordinates'
import { NATURAL_RESOURCES_TEMPLATE } from './natural-resources'
import { COMMUNITY_HELPERS_TEMPLATE } from './community-helpers'

// === Language Arts / Graphic Organizers templates (18) ===
import { VENN_DIAGRAM_TEMPLATE } from './venn-diagram'
import { PLOT_DIAGRAM_TEMPLATE } from './plot-diagram'
import { CONCEPT_WEB_TEMPLATE } from './concept-web'
import { SEQUENCE_CHAIN_TEMPLATE } from './sequence-chain'
import { T_CHART_TEMPLATE } from './t-chart'
import { KWL_CHART_TEMPLATE } from './kwl-chart'
import { CAUSE_EFFECT_TEMPLATE } from './cause-effect'
import { FACT_OPINION_TEMPLATE } from './fact-opinion'
import { LETTER_FORMAT_TEMPLATE } from './letter-format'
import { TEXT_STRUCTURE_TEMPLATE } from './text-structure'
import { WORD_PARTS_TEMPLATE } from './word-parts'
import { AUTHORS_PURPOSE_TEMPLATE } from './authors-purpose'
import { GENRE_CHART_TEMPLATE } from './genre-chart'
import { PARTS_OF_SPEECH_TEMPLATE } from './parts-of-speech'
import { SENTENCE_DIAGRAM_TEMPLATE } from './sentence-diagram'
import { STORY_ELEMENTS_TEMPLATE } from './story-elements'
import { TEXT_FEATURES_TEMPLATE } from './text-features'
import { WRITING_PROCESS_TEMPLATE } from './writing-process'

// === Health / Nutrition / Wellness templates (5) ===
import { NUTRITION_PLATE_TEMPLATE } from './nutrition-plate'
import { DENTAL_HEALTH_TEMPLATE } from './dental-health'
import { ACTIVITY_PYRAMID_TEMPLATE } from './activity-pyramid'
import { FEELINGS_EMOTIONS_TEMPLATE } from './feelings-emotions'
import { HAND_WASHING_STEPS_TEMPLATE } from './hand-washing-steps'

// === Art / Music templates (2) ===
import { COLOR_WHEEL_TEMPLATE } from './color-wheel'
import { MUSICAL_STAFF_TEMPLATE } from './musical-staff'

// === STEM / Engineering templates (4) ===
import { SCIENTIFIC_METHOD_TEMPLATE } from './scientific-method'
import { ENGINEERING_DESIGN_TEMPLATE } from './engineering-design'
import { DATA_TABLE_TEMPLATE } from './data-table'
import { CLASSIFICATION_KEY_TEMPLATE } from './classification-key'

// === Additional Science templates (8) ===
import { NATURAL_DISASTERS_TEMPLATE } from './natural-disasters'
import { DAY_NIGHT_ROTATION_TEMPLATE } from './day-night-rotation'
import { PROPERTIES_OF_MATTER_TEMPLATE } from './properties-of-matter'
import { MIXTURES_SOLUTIONS_TEMPLATE } from './mixtures-solutions'
import { STATIC_ELECTRICITY_TEMPLATE } from './static-electricity'
import { SHADOW_LIGHT_TEMPLATE } from './shadow-light'
import { PLANT_NEEDS_TEMPLATE } from './plant-needs'
import { DECOMPOSITION_CYCLE_TEMPLATE } from './decomposition-cycle'

export const ALL_TEMPLATES: TikzTemplate[] = [
  // Math (36)
  TEN_FRAMES_TEMPLATE,
  NUMBER_BONDS_TEMPLATE,
  NUMBER_LINES_TEMPLATE,
  BAR_MODELS_TEMPLATE,
  FRACTION_CIRCLES_TEMPLATE,
  FRACTION_BARS_TEMPLATE,
  AREA_MODELS_TEMPLATE,
  ARRAYS_GRIDS_TEMPLATE,
  PLACE_VALUE_TEMPLATE,
  SHAPES_BASIC_TEMPLATE,
  SHAPES_CLASSIFIED_TEMPLATE,
  ANGLES_LINES_TEMPLATE,
  BAR_GRAPHS_TEMPLATE,
  LINE_PLOTS_TEMPLATE,
  COORDINATE_PLANE_TEMPLATE,
  FACTOR_TREES_TEMPLATE,
  LONG_DIVISION_TEMPLATE,
  VOLUME_NETS_TEMPLATE,
  TAPE_DIAGRAMS_TEMPLATE,
  DOUBLE_NUMBER_LINES_TEMPLATE,
  PERCENTAGE_GRIDS_TEMPLATE,
  BOX_PLOTS_TEMPLATE,
  DOT_PLOTS_HISTOGRAMS_TEMPLATE,
  SYMMETRY_TEMPLATE,
  TALLY_MARKS_TEMPLATE,
  CLOCK_FACES_TEMPLATE,
  COIN_MONEY_TEMPLATE,
  EQUATION_BALANCE_TEMPLATE,
  MEASUREMENT_RULER_TEMPLATE,
  SKIP_COUNTING_TEMPLATE,
  THREE_D_SHAPES_TEMPLATE,
  PERIMETER_AREA_ELEMENTARY_TEMPLATE,
  EVEN_ODD_NUMBERS_TEMPLATE,
  MULTIPLICATION_TABLE_TEMPLATE,
  EXPANDED_FORM_TEMPLATE,
  ELAPSED_TIME_TEMPLATE,
  PROBABILITY_ELEMENTARY_TEMPLATE,
  PATTERN_SEQUENCES_ELEMENTARY_TEMPLATE,
  MEASUREMENT_CONVERSION_TEMPLATE,
  INPUT_OUTPUT_TABLE_TEMPLATE,
  ROUNDING_NUMBER_LINE_TEMPLATE,
  COMPARING_ORDERING_NUMBERS_TEMPLATE,
  // Life Science (11)
  LIFE_CYCLES_TEMPLATE,
  FOOD_CHAINS_WEBS_TEMPLATE,
  PLANT_ANATOMY_TEMPLATE,
  ANIMAL_CLASSIFICATION_TEMPLATE,
  HUMAN_BODY_SYSTEMS_TEMPLATE,
  BASIC_CELLS_TEMPLATE,
  HABITATS_ECOSYSTEMS_TEMPLATE,
  ANIMAL_ADAPTATIONS_TEMPLATE,
  HIBERNATION_MIGRATION_TEMPLATE,
  POLLINATION_PHOTOSYNTHESIS_TEMPLATE,
  INHERITED_LEARNED_TRAITS_TEMPLATE,
  // Earth & Space Science (13)
  WATER_CYCLE_TEMPLATE,
  ROCK_CYCLE_TEMPLATE,
  WEATHER_CLOUDS_TEMPLATE,
  SOLAR_SYSTEM_TEMPLATE,
  MOON_PHASES_TEMPLATE,
  EARTH_LAYERS_TEMPLATE,
  SEASONS_EARTH_TILT_TEMPLATE,
  LANDFORMS_TEMPLATE,
  EROSION_WEATHERING_TEMPLATE,
  SOIL_LAYERS_TEMPLATE,
  FOSSIL_FORMATION_TEMPLATE,
  RENEWABLE_NONRENEWABLE_TEMPLATE,
  RECYCLING_CONSERVATION_TEMPLATE,
  // Physical Science (9)
  FIVE_SENSES_TEMPLATE,
  STATES_OF_MATTER_TEMPLATE,
  SIMPLE_MACHINES_TEMPLATE,
  MAGNETS_TEMPLATE,
  LIGHT_OPTICS_TEMPLATE,
  SOUND_WAVES_TEMPLATE,
  ENERGY_TYPES_TEMPLATE,
  FORCES_MOTION_ELEMENTARY_TEMPLATE,
  SIMPLE_CIRCUITS_TEMPLATE,
  // Social Studies (10)
  TIMELINES_TEMPLATE,
  MAP_ELEMENTS_TEMPLATE,
  GOVERNMENT_STRUCTURE_TEMPLATE,
  COMMUNITY_MAP_TEMPLATE,
  FAMILY_TREE_TEMPLATE,
  WORLD_CONTINENTS_TEMPLATE,
  ECONOMICS_ELEMENTARY_TEMPLATE,
  MAP_GRID_COORDINATES_TEMPLATE,
  NATURAL_RESOURCES_TEMPLATE,
  COMMUNITY_HELPERS_TEMPLATE,
  // Language Arts / Graphic Organizers (18)
  VENN_DIAGRAM_TEMPLATE,
  PLOT_DIAGRAM_TEMPLATE,
  CONCEPT_WEB_TEMPLATE,
  SEQUENCE_CHAIN_TEMPLATE,
  T_CHART_TEMPLATE,
  KWL_CHART_TEMPLATE,
  CAUSE_EFFECT_TEMPLATE,
  FACT_OPINION_TEMPLATE,
  LETTER_FORMAT_TEMPLATE,
  TEXT_STRUCTURE_TEMPLATE,
  WORD_PARTS_TEMPLATE,
  AUTHORS_PURPOSE_TEMPLATE,
  GENRE_CHART_TEMPLATE,
  PARTS_OF_SPEECH_TEMPLATE,
  SENTENCE_DIAGRAM_TEMPLATE,
  STORY_ELEMENTS_TEMPLATE,
  TEXT_FEATURES_TEMPLATE,
  WRITING_PROCESS_TEMPLATE,
  // Health / Nutrition / Wellness (5)
  NUTRITION_PLATE_TEMPLATE,
  DENTAL_HEALTH_TEMPLATE,
  ACTIVITY_PYRAMID_TEMPLATE,
  FEELINGS_EMOTIONS_TEMPLATE,
  HAND_WASHING_STEPS_TEMPLATE,
  // Art / Music (2)
  COLOR_WHEEL_TEMPLATE,
  MUSICAL_STAFF_TEMPLATE,
  // STEM / Engineering (4)
  SCIENTIFIC_METHOD_TEMPLATE,
  ENGINEERING_DESIGN_TEMPLATE,
  DATA_TABLE_TEMPLATE,
  CLASSIFICATION_KEY_TEMPLATE,
  // Additional Science (8)
  NATURAL_DISASTERS_TEMPLATE,
  DAY_NIGHT_ROTATION_TEMPLATE,
  PROPERTIES_OF_MATTER_TEMPLATE,
  MIXTURES_SOLUTIONS_TEMPLATE,
  STATIC_ELECTRICITY_TEMPLATE,
  SHADOW_LIGHT_TEMPLATE,
  PLANT_NEEDS_TEMPLATE,
  DECOMPOSITION_CYCLE_TEMPLATE,
]

export {
  // Math (43)
  TEN_FRAMES_TEMPLATE,
  NUMBER_BONDS_TEMPLATE,
  NUMBER_LINES_TEMPLATE,
  BAR_MODELS_TEMPLATE,
  FRACTION_CIRCLES_TEMPLATE,
  FRACTION_BARS_TEMPLATE,
  AREA_MODELS_TEMPLATE,
  ARRAYS_GRIDS_TEMPLATE,
  PLACE_VALUE_TEMPLATE,
  SHAPES_BASIC_TEMPLATE,
  SHAPES_CLASSIFIED_TEMPLATE,
  ANGLES_LINES_TEMPLATE,
  BAR_GRAPHS_TEMPLATE,
  LINE_PLOTS_TEMPLATE,
  COORDINATE_PLANE_TEMPLATE,
  FACTOR_TREES_TEMPLATE,
  LONG_DIVISION_TEMPLATE,
  VOLUME_NETS_TEMPLATE,
  TAPE_DIAGRAMS_TEMPLATE,
  DOUBLE_NUMBER_LINES_TEMPLATE,
  PERCENTAGE_GRIDS_TEMPLATE,
  BOX_PLOTS_TEMPLATE,
  DOT_PLOTS_HISTOGRAMS_TEMPLATE,
  SYMMETRY_TEMPLATE,
  TALLY_MARKS_TEMPLATE,
  CLOCK_FACES_TEMPLATE,
  COIN_MONEY_TEMPLATE,
  EQUATION_BALANCE_TEMPLATE,
  MEASUREMENT_RULER_TEMPLATE,
  SKIP_COUNTING_TEMPLATE,
  THREE_D_SHAPES_TEMPLATE,
  PERIMETER_AREA_ELEMENTARY_TEMPLATE,
  EVEN_ODD_NUMBERS_TEMPLATE,
  MULTIPLICATION_TABLE_TEMPLATE,
  EXPANDED_FORM_TEMPLATE,
  ELAPSED_TIME_TEMPLATE,
  PROBABILITY_ELEMENTARY_TEMPLATE,
  PATTERN_SEQUENCES_ELEMENTARY_TEMPLATE,
  MEASUREMENT_CONVERSION_TEMPLATE,
  INPUT_OUTPUT_TABLE_TEMPLATE,
  ROUNDING_NUMBER_LINE_TEMPLATE,
  COMPARING_ORDERING_NUMBERS_TEMPLATE,
  // Life Science (11)
  LIFE_CYCLES_TEMPLATE,
  FOOD_CHAINS_WEBS_TEMPLATE,
  PLANT_ANATOMY_TEMPLATE,
  ANIMAL_CLASSIFICATION_TEMPLATE,
  HUMAN_BODY_SYSTEMS_TEMPLATE,
  BASIC_CELLS_TEMPLATE,
  HABITATS_ECOSYSTEMS_TEMPLATE,
  ANIMAL_ADAPTATIONS_TEMPLATE,
  HIBERNATION_MIGRATION_TEMPLATE,
  POLLINATION_PHOTOSYNTHESIS_TEMPLATE,
  INHERITED_LEARNED_TRAITS_TEMPLATE,
  // Earth & Space Science (13)
  WATER_CYCLE_TEMPLATE,
  ROCK_CYCLE_TEMPLATE,
  WEATHER_CLOUDS_TEMPLATE,
  SOLAR_SYSTEM_TEMPLATE,
  MOON_PHASES_TEMPLATE,
  EARTH_LAYERS_TEMPLATE,
  SEASONS_EARTH_TILT_TEMPLATE,
  LANDFORMS_TEMPLATE,
  EROSION_WEATHERING_TEMPLATE,
  SOIL_LAYERS_TEMPLATE,
  FOSSIL_FORMATION_TEMPLATE,
  RENEWABLE_NONRENEWABLE_TEMPLATE,
  RECYCLING_CONSERVATION_TEMPLATE,
  // Physical Science (9)
  FIVE_SENSES_TEMPLATE,
  STATES_OF_MATTER_TEMPLATE,
  SIMPLE_MACHINES_TEMPLATE,
  MAGNETS_TEMPLATE,
  LIGHT_OPTICS_TEMPLATE,
  SOUND_WAVES_TEMPLATE,
  ENERGY_TYPES_TEMPLATE,
  FORCES_MOTION_ELEMENTARY_TEMPLATE,
  SIMPLE_CIRCUITS_TEMPLATE,
  // Social Studies (10)
  TIMELINES_TEMPLATE,
  MAP_ELEMENTS_TEMPLATE,
  GOVERNMENT_STRUCTURE_TEMPLATE,
  COMMUNITY_MAP_TEMPLATE,
  FAMILY_TREE_TEMPLATE,
  WORLD_CONTINENTS_TEMPLATE,
  ECONOMICS_ELEMENTARY_TEMPLATE,
  MAP_GRID_COORDINATES_TEMPLATE,
  NATURAL_RESOURCES_TEMPLATE,
  COMMUNITY_HELPERS_TEMPLATE,
  // Language Arts / Graphic Organizers (18)
  VENN_DIAGRAM_TEMPLATE,
  PLOT_DIAGRAM_TEMPLATE,
  CONCEPT_WEB_TEMPLATE,
  SEQUENCE_CHAIN_TEMPLATE,
  T_CHART_TEMPLATE,
  KWL_CHART_TEMPLATE,
  CAUSE_EFFECT_TEMPLATE,
  FACT_OPINION_TEMPLATE,
  LETTER_FORMAT_TEMPLATE,
  TEXT_STRUCTURE_TEMPLATE,
  WORD_PARTS_TEMPLATE,
  AUTHORS_PURPOSE_TEMPLATE,
  GENRE_CHART_TEMPLATE,
  PARTS_OF_SPEECH_TEMPLATE,
  SENTENCE_DIAGRAM_TEMPLATE,
  STORY_ELEMENTS_TEMPLATE,
  TEXT_FEATURES_TEMPLATE,
  WRITING_PROCESS_TEMPLATE,
  // Health / Nutrition / Wellness (5)
  NUTRITION_PLATE_TEMPLATE,
  DENTAL_HEALTH_TEMPLATE,
  ACTIVITY_PYRAMID_TEMPLATE,
  FEELINGS_EMOTIONS_TEMPLATE,
  HAND_WASHING_STEPS_TEMPLATE,
  // Art / Music (2)
  COLOR_WHEEL_TEMPLATE,
  MUSICAL_STAFF_TEMPLATE,
  // STEM / Engineering (4)
  SCIENTIFIC_METHOD_TEMPLATE,
  ENGINEERING_DESIGN_TEMPLATE,
  DATA_TABLE_TEMPLATE,
  CLASSIFICATION_KEY_TEMPLATE,
  // Additional Science (8)
  NATURAL_DISASTERS_TEMPLATE,
  DAY_NIGHT_ROTATION_TEMPLATE,
  PROPERTIES_OF_MATTER_TEMPLATE,
  MIXTURES_SOLUTIONS_TEMPLATE,
  STATIC_ELECTRICITY_TEMPLATE,
  SHADOW_LIGHT_TEMPLATE,
  PLANT_NEEDS_TEMPLATE,
  DECOMPOSITION_CYCLE_TEMPLATE,
}
