'use client'

import {
  createContext,
  useContext,
  useCallback,
  useState,
  useEffect,
  type ReactNode,
} from 'react'
import { createClient } from '@/lib/supabase/client'

// ============================================================================
// Types
// ============================================================================

export type VisualComplexity = 'elementary' | 'middle_school' | 'high_school' | 'advanced'

export interface VisualPreferences {
  /** Whether to show visual diagrams by default */
  visualsEnabled: boolean
  /** Whether AI should auto-generate diagrams when explaining */
  autoGenerateDiagrams: boolean
  /** Visual complexity level based on user's grade/age */
  complexity: VisualComplexity
  /** Animation speed preference: 'slow' | 'normal' | 'fast' | 'instant' */
  animationSpeed: 'slow' | 'normal' | 'fast' | 'instant'
  /** Whether to show concrete examples (apples, objects) for elementary level */
  showConcreteExamples: boolean
  /** Whether to show full equations (hidden for elementary) */
  showEquations: boolean
}

interface VisualsContextValue {
  /** Current visual preferences */
  preferences: VisualPreferences
  /** Whether preferences are still loading */
  isLoading: boolean
  /** Toggle visuals on/off */
  toggleVisuals: () => void
  /** Toggle auto-generate diagrams */
  toggleAutoGenerate: () => void
  /** Set visual complexity level */
  setComplexity: (complexity: VisualComplexity) => void
  /** Set animation speed */
  setAnimationSpeed: (speed: VisualPreferences['animationSpeed']) => void
  /** Update any preference */
  updatePreference: <K extends keyof VisualPreferences>(
    key: K,
    value: VisualPreferences[K]
  ) => void
  /** Save preferences to database */
  savePreferences: () => Promise<void>
  /** Get animation duration based on speed preference */
  getAnimationDuration: (baseDuration: number) => number
}

// ============================================================================
// Default Preferences
// ============================================================================

const DEFAULT_PREFERENCES: VisualPreferences = {
  visualsEnabled: true, // ON by default as per plan
  autoGenerateDiagrams: true, // ON by default as per plan
  complexity: 'middle_school',
  animationSpeed: 'normal',
  showConcreteExamples: false,
  showEquations: true,
}

// ============================================================================
// Complexity Level Configurations
// ============================================================================

export const COMPLEXITY_CONFIG: Record<VisualComplexity, {
  showEquations: boolean
  defaultAnimationSpeed: VisualPreferences['animationSpeed']
  showConcreteExamples: boolean
  labelStyle: 'simple' | 'standard' | 'detailed'
}> = {
  elementary: {
    showEquations: false,
    defaultAnimationSpeed: 'slow',
    showConcreteExamples: true,
    labelStyle: 'simple',
  },
  middle_school: {
    showEquations: true,
    defaultAnimationSpeed: 'normal',
    showConcreteExamples: false,
    labelStyle: 'standard',
  },
  high_school: {
    showEquations: true,
    defaultAnimationSpeed: 'normal',
    showConcreteExamples: false,
    labelStyle: 'standard',
  },
  advanced: {
    showEquations: true,
    defaultAnimationSpeed: 'fast',
    showConcreteExamples: false,
    labelStyle: 'detailed',
  },
}

// ============================================================================
// Animation Speed Multipliers
// ============================================================================

const ANIMATION_SPEED_MULTIPLIERS: Record<VisualPreferences['animationSpeed'], number> = {
  slow: 2.0,
  normal: 1.0,
  fast: 0.5,
  instant: 0,
}

// ============================================================================
// Local Storage Key
// ============================================================================

const STORAGE_KEY = 'notesnap_visual_preferences'

// ============================================================================
// Context
// ============================================================================

const VisualsContext = createContext<VisualsContextValue | undefined>(undefined)

// ============================================================================
// Provider
// ============================================================================

interface VisualsProviderProps {
  children: ReactNode
}

export function VisualsProvider({ children }: VisualsProviderProps) {
  const [preferences, setPreferences] = useState<VisualPreferences>(DEFAULT_PREFERENCES)
  const [isLoading, setIsLoading] = useState(true)
  const supabase = createClient()

  // Load preferences from localStorage and database
  useEffect(() => {
    async function loadPreferences() {
      try {
        // First try localStorage for immediate loading
        if (typeof window !== 'undefined') {
          try {
            const stored = localStorage.getItem(STORAGE_KEY)
            if (stored) {
              const parsed = JSON.parse(stored) as Partial<VisualPreferences>
              setPreferences(prev => ({ ...prev, ...parsed }))
            }
          } catch {
            // localStorage not available or invalid JSON
          }
        }

        // Then try to load from database for logged-in users
        const { data: { user } } = await supabase.auth.getUser()
        if (user) {
          const { data: profile } = await supabase
            .from('user_learning_profile')
            .select('visual_preferences, grade')
            .eq('user_id', user.id)
            .single()

          if (profile?.visual_preferences) {
            const dbPreferences = profile.visual_preferences as Partial<VisualPreferences>
            setPreferences(prev => ({ ...prev, ...dbPreferences }))

            // Sync to localStorage
            if (typeof window !== 'undefined') {
              try {
                localStorage.setItem(STORAGE_KEY, JSON.stringify({ ...DEFAULT_PREFERENCES, ...dbPreferences }))
              } catch {
                // localStorage not available
              }
            }
          }

          // Auto-detect complexity from grade if not set
          if (profile?.grade) {
            const complexity = detectComplexityFromGrade(profile.grade)
            if (complexity) {
              setPreferences(prev => ({
                ...prev,
                complexity,
                ...COMPLEXITY_CONFIG[complexity],
              }))
            }
          }
        }
      } catch (error) {
        console.error('Error loading visual preferences:', error)
      } finally {
        setIsLoading(false)
      }
    }

    loadPreferences()
  }, [supabase])

  // Toggle visuals enabled
  const toggleVisuals = useCallback(() => {
    setPreferences(prev => {
      const updated = { ...prev, visualsEnabled: !prev.visualsEnabled }
      saveToLocalStorage(updated)
      return updated
    })
  }, [])

  // Toggle auto-generate diagrams
  const toggleAutoGenerate = useCallback(() => {
    setPreferences(prev => {
      const updated = { ...prev, autoGenerateDiagrams: !prev.autoGenerateDiagrams }
      saveToLocalStorage(updated)
      return updated
    })
  }, [])

  // Set complexity level
  const setComplexity = useCallback((complexity: VisualComplexity) => {
    const config = COMPLEXITY_CONFIG[complexity]
    setPreferences(prev => {
      const updated = {
        ...prev,
        complexity,
        showEquations: config.showEquations,
        showConcreteExamples: config.showConcreteExamples,
        animationSpeed: config.defaultAnimationSpeed,
      }
      saveToLocalStorage(updated)
      return updated
    })
  }, [])

  // Set animation speed
  const setAnimationSpeed = useCallback((speed: VisualPreferences['animationSpeed']) => {
    setPreferences(prev => {
      const updated = { ...prev, animationSpeed: speed }
      saveToLocalStorage(updated)
      return updated
    })
  }, [])

  // Update any preference
  const updatePreference = useCallback(<K extends keyof VisualPreferences>(
    key: K,
    value: VisualPreferences[K]
  ) => {
    setPreferences(prev => {
      const updated = { ...prev, [key]: value }
      saveToLocalStorage(updated)
      return updated
    })
  }, [])

  // Save preferences to database
  const savePreferences = useCallback(async () => {
    try {
      const { data: { user } } = await supabase.auth.getUser()
      if (!user) return

      await supabase
        .from('user_learning_profile')
        .update({ visual_preferences: preferences })
        .eq('user_id', user.id)
    } catch (error) {
      console.error('Error saving visual preferences:', error)
      throw error
    }
  }, [supabase, preferences])

  // Get animation duration based on speed preference
  const getAnimationDuration = useCallback((baseDuration: number): number => {
    return baseDuration * ANIMATION_SPEED_MULTIPLIERS[preferences.animationSpeed]
  }, [preferences.animationSpeed])

  const value: VisualsContextValue = {
    preferences,
    isLoading,
    toggleVisuals,
    toggleAutoGenerate,
    setComplexity,
    setAnimationSpeed,
    updatePreference,
    savePreferences,
    getAnimationDuration,
  }

  return (
    <VisualsContext.Provider value={value}>
      {children}
    </VisualsContext.Provider>
  )
}

// ============================================================================
// Hook
// ============================================================================

export function useVisuals(): VisualsContextValue {
  const context = useContext(VisualsContext)

  if (context === undefined) {
    throw new Error('useVisuals must be used within a VisualsProvider')
  }

  return context
}

// ============================================================================
// Helper Functions
// ============================================================================

function saveToLocalStorage(preferences: VisualPreferences): void {
  if (typeof window !== 'undefined') {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(preferences))
    } catch {
      // localStorage not available
    }
  }
}

function detectComplexityFromGrade(grade: string): VisualComplexity | null {
  const gradeNormalized = grade.toLowerCase()

  // Elementary: grades K-5 or year 1-6
  if (/^(k|[1-5]|year\s*[1-6]|grade\s*[1-5]|primary)/i.test(gradeNormalized)) {
    return 'elementary'
  }

  // Middle school: grades 6-8 or year 7-9
  if (/^([6-8]|year\s*(7|8|9)|grade\s*[6-8]|middle)/i.test(gradeNormalized)) {
    return 'middle_school'
  }

  // High school: grades 9-12 or year 10-13
  if (/^(9|1[0-2]|year\s*(1[0-3])|grade\s*(9|1[0-2])|high|ib|a-level|bagrut)/i.test(gradeNormalized)) {
    return 'high_school'
  }

  // Advanced: university, college, AP
  if (/^(university|college|ap|advanced|undergrad|grad)/i.test(gradeNormalized)) {
    return 'advanced'
  }

  return null
}

export default VisualsContext
