'use client'

import { useVisuals } from '@/contexts/VisualsContext'
import { useTranslations } from 'next-intl'

interface DiagramToggleProps {
  /** Compact mode shows just the icon + switch (no label text) */
  compact?: boolean
  className?: string
}

/**
 * Toggle switch for enabling/disabling AI diagram generation.
 * Reads from and writes to VisualsContext (persisted in localStorage + DB).
 * Can be placed in any feature UI (courses, practice, homework, prepare).
 */
export default function DiagramToggle({ compact = false, className = '' }: DiagramToggleProps) {
  const { preferences, toggleAutoGenerate } = useVisuals()
  const t = useTranslations('common')
  const enabled = preferences.autoGenerateDiagrams

  return (
    <button
      type="button"
      onClick={toggleAutoGenerate}
      className={`flex items-center gap-2 px-2 py-1 rounded-lg text-xs font-medium transition-colors
        ${enabled
          ? 'bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-300'
          : 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-400'
        } hover:opacity-80 ${className}`}
      title={enabled ? (t('settings.diagramsEnabled') || 'AI Diagrams: ON') : (t('settings.diagramsDisabled') || 'AI Diagrams: OFF')}
    >
      {/* Diagram icon */}
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
        <rect x="3" y="3" width="18" height="18" rx="2" />
        <path d="M3 9h18" />
        <path d="M9 21V9" />
        <circle cx="16" cy="15" r="2" />
      </svg>
      {!compact && (
        <span>{enabled ? 'Diagrams' : 'Diagrams'}</span>
      )}
      {/* Toggle switch — force LTR so dot positioning works in RTL layouts */}
      <div dir="ltr" className={`relative w-7 h-4 rounded-full transition-colors ${enabled ? 'bg-violet-500' : 'bg-gray-300 dark:bg-gray-600'}`}>
        <div className={`absolute left-0 top-0.5 w-3 h-3 rounded-full bg-white transition-transform shadow-sm ${enabled ? 'translate-x-3.5' : 'translate-x-0.5'}`} />
      </div>
    </button>
  )
}
