'use client'

import { useMemo, useCallback } from 'react'
import { useVisuals, type VisualComplexity, COMPLEXITY_CONFIG } from '@/contexts/VisualsContext'

// ============================================================================
// Types
// ============================================================================

export interface VisualPreferenceOptions {
  /** Override the enabled state (useful for specific contexts) */
  forceEnabled?: boolean
  /** Override complexity level */
  forceComplexity?: VisualComplexity
}

export interface UseVisualPreferenceReturn {
  /** Whether visuals should be shown */
  shouldShowVisuals: boolean
  /** Whether AI should auto-generate diagrams */
  shouldAutoGenerate: boolean
  /** Current complexity level */
  complexity: VisualComplexity
  /** Whether to show full equations */
  showEquations: boolean
  /** Whether to show concrete examples (apples, objects) */
  showConcreteExamples: boolean
  /** Animation duration multiplier (0 for instant) */
  animationMultiplier: number
  /** Get scaled animation duration */
  getAnimationDuration: (baseDuration: number) => number
  /** Toggle visuals on/off */
  toggleVisuals: () => void
  /** Label style based on complexity */
  labelStyle: 'simple' | 'standard' | 'detailed'
  /** Whether preferences are loading */
  isLoading: boolean
}

// ============================================================================
// Hook
// ============================================================================

/**
 * useVisualPreference - Hook for components to access and respect visual preferences
 *
 * This hook provides an easy interface for diagram components to:
 * 1. Check if they should render at all
 * 2. Get the appropriate complexity level
 * 3. Adjust animations based on user preference
 * 4. Determine what to show (equations, concrete examples, etc.)
 *
 * @example
 * // In a diagram component
 * const { shouldShowVisuals, complexity, getAnimationDuration } = useVisualPreference()
 *
 * if (!shouldShowVisuals) return null
 *
 * const duration = getAnimationDuration(500) // Returns 1000ms for slow, 500ms for normal, etc.
 *
 * @example
 * // With forced settings
 * const { shouldShowVisuals } = useVisualPreference({ forceEnabled: true })
 */
export function useVisualPreference(options: VisualPreferenceOptions = {}): UseVisualPreferenceReturn {
  const {
    preferences,
    isLoading,
    toggleVisuals,
    getAnimationDuration,
  } = useVisuals()

  const { forceEnabled, forceComplexity } = options

  // Determine effective complexity
  const complexity = forceComplexity || preferences.complexity

  // Get complexity configuration
  const complexityConfig = COMPLEXITY_CONFIG[complexity]

  // Determine if visuals should be shown
  const shouldShowVisuals = useMemo(() => {
    if (forceEnabled !== undefined) return forceEnabled
    return preferences.visualsEnabled
  }, [forceEnabled, preferences.visualsEnabled])

  // Determine if AI should auto-generate
  const shouldAutoGenerate = useMemo(() => {
    return preferences.visualsEnabled && preferences.autoGenerateDiagrams
  }, [preferences.visualsEnabled, preferences.autoGenerateDiagrams])

  // Calculate animation multiplier
  const animationMultiplier = useMemo(() => {
    switch (preferences.animationSpeed) {
      case 'slow': return 2.0
      case 'normal': return 1.0
      case 'fast': return 0.5
      case 'instant': return 0
      default: return 1.0
    }
  }, [preferences.animationSpeed])

  // Memoized getAnimationDuration wrapper
  const getAnimationDurationMemoized = useCallback((baseDuration: number) => {
    return getAnimationDuration(baseDuration)
  }, [getAnimationDuration])

  return {
    shouldShowVisuals,
    shouldAutoGenerate,
    complexity,
    showEquations: preferences.showEquations,
    showConcreteExamples: preferences.showConcreteExamples,
    animationMultiplier,
    getAnimationDuration: getAnimationDurationMemoized,
    toggleVisuals,
    labelStyle: complexityConfig.labelStyle,
    isLoading,
  }
}

// ============================================================================
// Utility Hook: Check if should render diagram
// ============================================================================

/**
 * useShouldRenderDiagram - Simple hook to check if a diagram should render
 *
 * @example
 * const shouldRender = useShouldRenderDiagram()
 * if (!shouldRender) return null
 */
export function useShouldRenderDiagram(): boolean {
  const { shouldShowVisuals, isLoading } = useVisualPreference()

  // Don't render while loading (to avoid flash)
  if (isLoading) return false

  return shouldShowVisuals
}

// ============================================================================
// Utility Hook: Get diagram animation settings
// ============================================================================

export interface DiagramAnimationSettings {
  duration: number
  stagger: number
  enabled: boolean
}

/**
 * useDiagramAnimations - Get animation settings for diagrams
 *
 * @param baseDuration - Base animation duration in ms (default: 500)
 * @param baseStagger - Base stagger delay in ms (default: 100)
 *
 * @example
 * const { duration, stagger, enabled } = useDiagramAnimations(500, 100)
 */
export function useDiagramAnimations(
  baseDuration: number = 500,
  baseStagger: number = 100
): DiagramAnimationSettings {
  const { getAnimationDuration, animationMultiplier } = useVisualPreference()

  return useMemo(() => ({
    duration: getAnimationDuration(baseDuration),
    stagger: getAnimationDuration(baseStagger),
    enabled: animationMultiplier > 0,
  }), [getAnimationDuration, baseDuration, baseStagger, animationMultiplier])
}

// ============================================================================
// Utility Hook: Get complexity-based settings
// ============================================================================

export interface ComplexitySettings {
  complexity: VisualComplexity
  showEquations: boolean
  showConcreteExamples: boolean
  labelStyle: 'simple' | 'standard' | 'detailed'
  fontSize: {
    small: number
    normal: number
    large: number
  }
}

/**
 * useComplexitySettings - Get visual complexity settings for adaptive rendering
 *
 * @example
 * const { showEquations, fontSize } = useComplexitySettings()
 *
 * return showEquations ? <Equation /> : <SimpleLabel />
 */
export function useComplexitySettings(): ComplexitySettings {
  const { complexity, showEquations, showConcreteExamples, labelStyle } = useVisualPreference()

  // Font sizes based on complexity (larger for younger students)
  const fontSize = useMemo(() => {
    switch (complexity) {
      case 'elementary':
        return { small: 14, normal: 18, large: 24 }
      case 'middle_school':
        return { small: 12, normal: 16, large: 20 }
      case 'high_school':
        return { small: 11, normal: 14, large: 18 }
      case 'advanced':
        return { small: 10, normal: 13, large: 16 }
      default:
        return { small: 12, normal: 14, large: 18 }
    }
  }, [complexity])

  return {
    complexity,
    showEquations,
    showConcreteExamples,
    labelStyle,
    fontSize,
  }
}

export default useVisualPreference
