import { SYSTEM_PROMPT } from './system-prompt';
import { executeCode, detectMode, type RenderMode } from './e2b-executor';
import { generateTikzDiagram } from './tikz-executor';
import { generateRecraftDiagram, type OverlayLabel } from './recraft-executor';
import { routeQuestion, type Pipeline } from './router';
import Anthropic from '@anthropic-ai/sdk';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY!,
});

export type { Pipeline } from './router';

export interface DiagramResult {
  imageUrl: string;
  pipeline: Pipeline;
  attempts: number;
  code?: string;
  overlay?: OverlayLabel[];
  qaVerdict?: string;
}

export interface DiagramError {
  error: string;
  code?: string;
  pipeline?: Pipeline;
}

// ─── AI Quality Assurance ───────────────────────────────────────────────────

interface QAVerdict {
  pass: boolean;
  issues: string;
}

const QA_PROMPT = `You are a strict quality reviewer for educational diagrams made for students.

The student asked: "{QUESTION}"
This diagram was generated by the "{PIPELINE}" pipeline.

Evaluate the diagram on these criteria:

1. CORRECTNESS — Is the content mathematically/scientifically accurate? Are labels, values, and relationships correct?
2. COMPLETENESS — Does the diagram show everything the student asked for? Are key elements missing?
3. READABILITY — Can a student understand this? Is text readable, not overlapping, not cut off? Are colors distinguishable?
4. VISUAL QUALITY — Does it look clean and professional? No artifacts, no broken rendering, no garbled text?

Respond with EXACTLY this JSON format, nothing else:
{"pass": true, "issues": ""}

Or if there are problems:
{"pass": false, "issues": "Brief description of what's wrong and how to fix it. Max 200 chars."}

IMPORTANT:
- Be strict on correctness — wrong math, wrong labels, or wrong structure means FAIL
- Be lenient on minor aesthetic issues — slightly imperfect spacing or colors are OK
- If the image is mostly blank, garbled, or clearly broken → FAIL
- If the image shows the right concept but could be slightly better → PASS
- Recraft images won't have labels (those are overlaid separately) — don't fail for missing labels on recraft`;

/**
 * Send a generated diagram to Claude Vision for quality check.
 */
async function qaCheckDiagram(
  imageUrl: string,
  question: string,
  pipeline: Pipeline,
): Promise<QAVerdict> {
  try {
    let base64Image: string;
    let mediaType: 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp' = 'image/png';

    if (imageUrl.startsWith('data:image/png;base64,')) {
      // E2B returns base64 data URL
      base64Image = imageUrl.replace('data:image/png;base64,', '');
    } else {
      // TikZ and Recraft return HTTP URLs
      const response = await fetch(imageUrl);
      const buffer = await response.arrayBuffer();
      base64Image = Buffer.from(buffer).toString('base64');
      const ct = response.headers.get('content-type') || 'image/png';
      if (['image/jpeg', 'image/png', 'image/gif', 'image/webp'].includes(ct)) {
        mediaType = ct as typeof mediaType;
      }
    }

    const qaMessage = await anthropic.messages.create({
      model: 'claude-sonnet-4-20250514',
      max_tokens: 300,
      messages: [
        {
          role: 'user',
          content: [
            {
              type: 'image',
              source: { type: 'base64', media_type: mediaType, data: base64Image },
            },
            {
              type: 'text',
              text: QA_PROMPT
                .replace('{QUESTION}', question)
                .replace('{PIPELINE}', pipeline),
            },
          ],
        },
      ],
    });

    const textBlock = qaMessage.content.find((b) => b.type === 'text');
    if (!textBlock || textBlock.type !== 'text') {
      return { pass: true, issues: '' };
    }

    let jsonStr = textBlock.text.trim();
    // Extract JSON from possible markdown fences
    const fenceMatch = jsonStr.match(/```(?:json)?\s*\n?([\s\S]*?)```/);
    if (fenceMatch) jsonStr = fenceMatch[1].trim();
    // Find JSON object
    const objMatch = jsonStr.match(/\{[\s\S]*\}/);
    if (objMatch) jsonStr = objMatch[0];

    const parsed = JSON.parse(jsonStr);
    return {
      pass: !!parsed.pass,
      issues: typeof parsed.issues === 'string' ? parsed.issues : '',
    };
  } catch (err) {
    console.error('[QA] Vision check failed, passing by default:', err);
    // If QA itself fails, don't block the user
    return { pass: true, issues: '' };
  }
}

// ─── E2B Code Generation ────────────────────────────────────────────────────

/**
 * Ask Claude to generate E2B code (LaTeX or matplotlib).
 * If qaFeedback is provided, it's folded into the prompt so the model avoids the same mistake.
 */
async function generateE2BCode(
  question: string,
  previousError?: string,
  qaFeedback?: string,
): Promise<string> {
  let userMessage: string;

  if (previousError) {
    userMessage = `The previous code produced this error:\n\`\`\`\n${previousError}\n\`\`\`\n\nPlease fix the code and try again. Original question: ${question}`;
  } else if (qaFeedback) {
    userMessage = `A quality reviewer checked the previous diagram and found these issues:\n"${qaFeedback}"\n\nRegenerate the diagram fixing these problems. Original question: ${question}`;
  } else {
    userMessage = question;
  }

  const response = await anthropic.messages.create({
    model: 'claude-sonnet-4-5-20250929',
    max_tokens: 8192,
    system: SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userMessage }],
  });

  const textBlock = response.content.find((block) => block.type === 'text');
  if (!textBlock || textBlock.type !== 'text') {
    throw new Error('No text response from Claude');
  }

  let code = textBlock.text.trim();
  if (code.startsWith('```python')) {
    code = code.slice('```python'.length);
  } else if (code.startsWith('```latex') || code.startsWith('```tex')) {
    code = code.slice(code.indexOf('\n') + 1);
  } else if (code.startsWith('```')) {
    code = code.slice('```'.length);
  }
  if (code.endsWith('```')) {
    code = code.slice(0, -'```'.length);
  }
  return code.trim();
}

/**
 * Generate a diagram using E2B (LaTeX or matplotlib).
 * Includes compilation retries + AI QA loop.
 */
async function generateE2BDiagram(
  question: string,
  forcedMode?: 'latex' | 'matplotlib'
): Promise<DiagramResult | DiagramError> {
  const MAX_COMPILE_RETRIES = 3;
  const MAX_QA_RETRIES = 2;
  let lastError: string | undefined;
  let code: string = '';
  let mode: RenderMode = forcedMode || 'matplotlib';
  let qaFeedback: string | undefined;

  for (let qaRound = 0; qaRound <= MAX_QA_RETRIES; qaRound++) {
    lastError = undefined;

    for (let attempt = 1; attempt <= MAX_COMPILE_RETRIES; attempt++) {
      try {
        code = await generateE2BCode(
          question,
          lastError,
          attempt === 1 ? qaFeedback : undefined,
        );
        mode = forcedMode || detectMode(code);

        console.log(`[E2B QA:${qaRound} Attempt:${attempt}] Mode: ${mode}, Code length: ${code.length}`);

        const result = await executeCode(code, mode);

        if (result.png) {
          const imageUrl = `data:image/png;base64,${result.png}`;

          // QA check (skip on last allowed round — just return what we have)
          if (qaRound < MAX_QA_RETRIES) {
            console.log(`[QA] Checking E2B result (round ${qaRound + 1})...`);
            const verdict = await qaCheckDiagram(imageUrl, question, mode === 'latex' ? 'e2b-latex' : 'e2b-matplotlib');

            if (!verdict.pass) {
              console.log(`[QA] FAILED: ${verdict.issues}`);
              qaFeedback = verdict.issues;
              break; // break compile loop, start new QA round
            }

            console.log(`[QA] PASSED`);
            return {
              imageUrl,
              pipeline: mode === 'latex' ? 'e2b-latex' : 'e2b-matplotlib',
              attempts: qaRound * MAX_COMPILE_RETRIES + attempt,
              code,
              qaVerdict: 'pass',
            };
          }

          // Last QA round — return regardless
          return {
            imageUrl,
            pipeline: mode === 'latex' ? 'e2b-latex' : 'e2b-matplotlib',
            attempts: qaRound * MAX_COMPILE_RETRIES + attempt,
            code,
            qaVerdict: qaRound > 0 ? 'pass-after-retry' : 'skipped',
          };
        }

        lastError = result.error;
        console.log(`[E2B Attempt ${attempt}] Failed: ${lastError?.slice(0, 200)}`);
      } catch (err) {
        lastError = err instanceof Error ? err.message : 'Unknown error';
        console.log(`[E2B Attempt ${attempt}] Error: ${lastError}`);
      }
    }

    // If we exhausted compile retries without producing an image, stop
    if (lastError) break;
  }

  return {
    error: `Failed after retries. Last error: ${lastError}`,
    code,
    pipeline: mode === 'latex' ? 'e2b-latex' : 'e2b-matplotlib',
  };
}

// ─── Main Entry Point ───────────────────────────────────────────────────────

/**
 * Generate a diagram for a student question.
 * Routes to the best pipeline, generates, runs AI QA, retries if needed.
 */
export async function generateDiagram(
  question: string,
  forcePipeline?: Pipeline
): Promise<DiagramResult | DiagramError> {
  const pipeline = forcePipeline || routeQuestion(question);
  console.log(`[Router] Question: "${question.slice(0, 80)}..." → Pipeline: ${pipeline}`);

  switch (pipeline) {
    case 'e2b-latex':
      return generateE2BDiagram(question, 'latex');

    case 'e2b-matplotlib':
      return generateE2BDiagram(question, 'matplotlib');

    case 'tikz':
      return generateTikzWithQA(question);

    case 'recraft':
      return generateRecraftWithQA(question);
  }
}

// ─── TikZ + QA ──────────────────────────────────────────────────────────────

async function generateTikzWithQA(
  question: string,
): Promise<DiagramResult | DiagramError> {
  const MAX_QA_RETRIES = 2;

  for (let qaRound = 0; qaRound <= MAX_QA_RETRIES; qaRound++) {
    const tikzResult = await generateTikzDiagram(question);

    if ('error' in tikzResult) {
      return { error: tikzResult.error, code: tikzResult.tikzCode, pipeline: 'tikz' };
    }

    // QA check (skip on last round)
    if (qaRound < MAX_QA_RETRIES) {
      console.log(`[QA] Checking TikZ result (round ${qaRound + 1})...`);
      const verdict = await qaCheckDiagram(tikzResult.imageUrl, question, 'tikz');

      if (!verdict.pass) {
        console.log(`[QA] TikZ FAILED: ${verdict.issues}`);
        // For TikZ, we can't easily inject feedback into the template system,
        // so we append the feedback to the question for the next attempt
        question = `${question}\n\nIMPORTANT: The previous diagram had these issues that MUST be fixed: ${verdict.issues}`;
        continue;
      }

      console.log(`[QA] TikZ PASSED`);
    }

    return {
      imageUrl: tikzResult.imageUrl,
      pipeline: 'tikz',
      attempts: qaRound + 1,
      code: tikzResult.tikzCode,
      qaVerdict: qaRound > 0 ? 'pass-after-retry' : 'pass',
    };
  }

  // Shouldn't reach here, but just in case
  return { error: 'TikZ QA failed after retries', pipeline: 'tikz' };
}

// ─── Recraft + QA ───────────────────────────────────────────────────────────

async function generateRecraftWithQA(
  question: string,
): Promise<DiagramResult | DiagramError> {
  const MAX_QA_RETRIES = 2;

  for (let qaRound = 0; qaRound <= MAX_QA_RETRIES; qaRound++) {
    const recraftResult = await generateRecraftDiagram(question);

    if ('error' in recraftResult) {
      return { error: recraftResult.error, pipeline: 'recraft' };
    }

    // QA check (skip on last round)
    if (qaRound < MAX_QA_RETRIES) {
      console.log(`[QA] Checking Recraft result (round ${qaRound + 1})...`);
      const verdict = await qaCheckDiagram(recraftResult.imageUrl, question, 'recraft');

      if (!verdict.pass) {
        console.log(`[QA] Recraft FAILED: ${verdict.issues}`);
        // For Recraft, append feedback to question so the prompt rewriter avoids the issue
        question = `${question}\n\nIMPORTANT: The previous illustration had these issues that MUST be fixed: ${verdict.issues}`;
        continue;
      }

      console.log(`[QA] Recraft PASSED`);
    }

    return {
      imageUrl: recraftResult.imageUrl,
      pipeline: 'recraft',
      attempts: qaRound + 1,
      overlay: recraftResult.overlay,
      qaVerdict: qaRound > 0 ? 'pass-after-retry' : 'pass',
    };
  }

  return { error: 'Recraft QA failed after retries', pipeline: 'recraft' };
}
