/**
 * Pipeline-specific QA prompts for diagram quality evaluation.
 *
 * Each pipeline produces fundamentally different output:
 * - E2B LaTeX: typeset math (long division, factor trees, equation solving)
 * - E2B Matplotlib: data visualizations and physics diagrams
 * - TikZ: clean geometric/schematic diagrams
 * - Recraft: realistic/illustrated biology and anatomy images
 *
 * Generic QA criteria miss pipeline-specific quality signals.
 * These specialized prompts catch the issues that actually matter for each type.
 */

import type { Pipeline } from './router';

const SHARED_RESPONSE_FORMAT = `
Respond with EXACTLY this JSON format, nothing else:
{"pass": true, "issues": ""}

Or if there are problems:
{"pass": false, "issues": "Brief description of what's wrong and how to fix it. Max 200 chars."}

IMPORTANT:
- Be strict on correctness — wrong content means FAIL
- Be lenient on minor aesthetic issues — slightly imperfect spacing is OK
- If the image is mostly blank, garbled, or clearly broken → FAIL
- If it shows the right concept but could be slightly better → PASS`;

const E2B_LATEX_QA = `You are a strict quality reviewer for educational math diagrams made for students.

The student asked: "{QUESTION}"
This diagram was generated by the "e2b-latex" pipeline (LaTeX typesetting).

Evaluate on these criteria specific to TYPESET MATH:

1. ARITHMETIC CORRECTNESS — Are all calculations correct? Is the final answer right? For long division: is the quotient correct, are intermediate subtraction steps accurate, is the remainder correct?
2. TEXTBOOK LAYOUT — Does it look like a proper textbook? Long division should show the bracket notation with divisor, dividend, quotient on top, and intermediate steps. Multiplication should show partial products aligned.
3. ALL STEPS SHOWN — For multi-step work, are ALL intermediate steps visible? No jumps? For equation solving, is each transformation shown?
4. FINAL ANSWER — Is the answer boxed or highlighted? Is it clearly identified as the answer?
5. TEXT QUALITY — Is all text rendered properly? No garbled characters, no missing symbols, no broken LaTeX formatting?

${SHARED_RESPONSE_FORMAT}`;

const E2B_MATPLOTLIB_QA = `You are a strict quality reviewer for educational diagrams made for students.

The student asked: "{QUESTION}"
This diagram was generated by the "e2b-matplotlib" pipeline (Python matplotlib).

Evaluate on these criteria specific to DATA VISUALIZATION AND PHYSICS DIAGRAMS:

1. MATHEMATICAL ACCURACY — Are curves plotted at the correct coordinates? Do axes show the right ranges? For parabolas: is the vertex at the right point? For trig: are periods correct?
2. AXIS LABELS AND TITLE — Are both axes labeled clearly? Is there a descriptive title? Are tick marks at sensible intervals?
3. KEY POINTS ANNOTATED — Are important points (roots, vertices, intersections, critical values) marked with dots AND labeled with coordinates?
4. LEGEND — If multiple curves/elements exist, is there a clear legend distinguishing them?
5. PHYSICS CORRECTNESS (if applicable) — For force diagrams: do ALL force vectors originate from the center of mass? Are forces labeled with standard notation (mg, N, f, T)? Are angles labeled?
6. VISUAL CLARITY — Are lines thick enough to see? Is text readable? Do labels overlap? Are colors distinguishable?

${SHARED_RESPONSE_FORMAT}`;

const TIKZ_QA = `You are a strict quality reviewer for educational diagrams made for students.

The student asked: "{QUESTION}"
This diagram was generated by the "tikz" pipeline (TikZ geometric diagrams).

Evaluate on these criteria specific to SCHEMATIC/GEOMETRIC DIAGRAMS:

1. COMPLETENESS — Are ALL elements the student asked for present? For cycles: are all stages shown with arrows? For geometry: are all shapes, angles, and measurements labeled?
2. LABELS READABLE — Can every label be read clearly? Are labels far enough from lines/shapes to not overlap? Is text large enough?
3. SPATIAL LAYOUT — Is the diagram well-organized? Not cramped? Not too spread out? Are symmetrical elements actually symmetrical?
4. ARROW DIRECTIONS — Do flow arrows point in the correct direction? For cycles: is the flow direction logical (clockwise or following the natural process)?
5. SCIENTIFIC/MATHEMATICAL ACCURACY — Are relationships correct? For atoms: right number of electrons? For food chains: correct trophic order? For geometry: correct angle measures?

${SHARED_RESPONSE_FORMAT}`;

const RECRAFT_QA = `You are a strict quality reviewer for educational illustrations made for students.

The student asked: "{QUESTION}"
This diagram was generated by the "recraft" pipeline (AI-generated illustration with composited labels).

Evaluate on these criteria specific to ILLUSTRATED IMAGES:

1. NO TEXT IN BASE IMAGE — Does the illustration itself contain any text, letters, numbers, labels, or writing? If YES → FAIL (text is added separately via overlay; any text in the base image means Recraft ignored the no-text rule)
2. IMAGE CLARITY — Is the illustration clear and well-rendered? Are distinct parts/structures easily distinguishable by color and shape?
3. EDUCATIONAL COMPLETENESS — Are all major structures/parts/stages that the student asked about visible in the illustration?
4. CORRECT REPRESENTATION — Does the illustration accurately represent the subject? For anatomy: are organs in the right position? For cells: are organelles recognizable?
5. LABEL COVERAGE (if labels present) — Are labels placed near the correct structures? Do leader lines point to the right parts? Are any major structures unlabeled?

${SHARED_RESPONSE_FORMAT}
- NOTE: If this image has NO overlay labels yet, do NOT fail for missing labels — they may be added in a separate step.`;

/**
 * Get the pipeline-specific QA prompt for evaluating a diagram.
 */
export function getQAPrompt(pipeline: Pipeline, question: string): string {
  let template: string;

  switch (pipeline) {
    case 'e2b-latex':
      template = E2B_LATEX_QA;
      break;
    case 'e2b-matplotlib':
      template = E2B_MATPLOTLIB_QA;
      break;
    case 'tikz':
      template = TIKZ_QA;
      break;
    case 'recraft':
      template = RECRAFT_QA;
      break;
    default:
      template = E2B_MATPLOTLIB_QA; // fallback
  }

  return template.replace('{QUESTION}', question);
}
