/**
 * Step Capture Orchestrator
 *
 * Called during diagram generation to pre-render step-by-step images.
 * Coordinates per-pipeline step capture, uploads to Supabase Storage,
 * and returns StepImage[] to embed in DiagramResult.
 *
 * Each pipeline has its own capture strategy:
 * - TikZ: parse STEP markers → compile cumulative subsets via QuickLaTeX
 * - Matplotlib: inject savefig calls → single E2B run → extract N PNGs
 * - LaTeX: parse STEP markers → compile cumulative subsets via E2B
 */

import type { Pipeline } from '../router'
import type { StepImage } from '@/components/homework/diagram/types'
import { captureTikzSteps } from './tikz-steps'
import { captureMatplotlibSteps } from './matplotlib-steps'
import { captureLatexSteps } from './latex-steps'
import { parseStepMetadata } from './parse-metadata'
import { uploadStepImages, generateDiagramHash } from './upload-steps'

/** Feature flag — can be disabled via env var */
const STEP_CAPTURE_ENABLED = process.env.STEP_CAPTURE_ENABLED !== 'false'

export interface StepCaptureResult {
  stepImages: StepImage[]
  captureTimeMs: number
}

/**
 * Capture step images from generated diagram code.
 *
 * @param code - The complete code generated by AI (TikZ/Python/LaTeX)
 * @param pipeline - Which pipeline generated the code
 * @param metadataText - AI response text containing step metadata JSON
 * @param userId - User ID for storage paths
 * @param question - Original question (for hash generation)
 * @returns StepImage array (empty on failure, never throws)
 */
export async function captureSteps(
  code: string,
  pipeline: Pipeline,
  metadataText: string,
  userId: string,
  question: string,
): Promise<StepCaptureResult> {
  if (!STEP_CAPTURE_ENABLED) {
    return { stepImages: [], captureTimeMs: 0 }
  }

  const startTime = Date.now()

  try {
    // 1. Parse metadata from AI response
    const metadata = parseStepMetadata(metadataText)
    if (!metadata || metadata.length === 0) {
      console.warn('[StepCapture] No valid metadata found')
      return { stepImages: [], captureTimeMs: Date.now() - startTime }
    }

    // 2. Capture step images based on pipeline
    let buffers: (Buffer | null)[]

    switch (pipeline) {
      case 'tikz': {
        const result = await captureTikzSteps(code)
        buffers = result.buffers
        break
      }
      case 'e2b-matplotlib': {
        const result = await captureMatplotlibSteps(code)
        buffers = result.buffers
        break
      }
      case 'e2b-latex': {
        const result = await captureLatexSteps(code)
        buffers = result.buffers
        break
      }
      default:
        // Recraft and other pipelines don't support step capture
        return { stepImages: [], captureTimeMs: Date.now() - startTime }
    }

    if (buffers.length === 0) {
      return { stepImages: [], captureTimeMs: Date.now() - startTime }
    }

    // 3. Upload to Supabase Storage
    const validBuffers = buffers.filter((b): b is Buffer => b !== null)
    if (validBuffers.length === 0) {
      console.warn('[StepCapture] All step compilations failed')
      return { stepImages: [], captureTimeMs: Date.now() - startTime }
    }

    const diagramHash = generateDiagramHash(question, pipeline)
    const urls = await uploadStepImages(validBuffers, userId, diagramHash)

    // 4. Combine URLs with metadata
    const stepImages: StepImage[] = []
    let bufferIdx = 0

    for (let i = 0; i < buffers.length && i < metadata.length; i++) {
      if (buffers[i] !== null) {
        const url = urls[bufferIdx]
        bufferIdx++

        if (url) {
          stepImages.push({
            url,
            label: metadata[i].label,
            labelHe: metadata[i].labelHe,
            explanation: metadata[i].explanation,
            explanationHe: metadata[i].explanationHe,
          })
        }
      }
      // Skip steps where compilation failed — partial is fine
    }

    const captureTimeMs = Date.now() - startTime
    console.log(`[StepCapture] Completed: ${stepImages.length} steps in ${captureTimeMs}ms`)

    return { stepImages, captureTimeMs }
  } catch (err) {
    console.error('[StepCapture] Unexpected error:', err)
    return { stepImages: [], captureTimeMs: Date.now() - startTime }
  }
}
