-- Add diagram and visual_update columns to homework_turns
-- These store diagram state (engine_image PNG data, step sequences)
-- and visual updates generated by the tutor engine
ALTER TABLE homework_turns
  ADD COLUMN IF NOT EXISTS diagram JSONB,
  ADD COLUMN IF NOT EXISTS visual_update JSONB;

-- Add comment for documentation
COMMENT ON COLUMN homework_turns.diagram IS 'Diagram state (engine_image or step_sequence) generated by tutor engine';
COMMENT ON COLUMN homework_turns.visual_update IS 'Visual solving panel update generated by tutor engine';
